{{- if include "isCertConfigValid" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-s3proxy-tls
spec:
  commonName: {{ include "checkCertDefaultValue" (dict "HasValue" .Values.cert.commonName "Context" .) }}
  dnsNames:
  - {{ include "checkCertDefaultValue" (dict "HasValue" .Values.cert.dnsName "Context" .) }}
  issuerRef:
    group: cert-manager.io
    kind: {{ .Values.cert.issuerRefKind }}
    name: {{ .Values.cert.issuerRefName | quote }}
  secretName: cert-s3proxy-tls
  usages:
  - digital signature
  - key encipherment
{{- end }}