{{- if .Values.enableCertFromCertManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-s3proxy-tls
spec:
  commonName: '*.s3proxy.internal.company.com'
  dnsNames:
  - s3proxy.s3proxy.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: internal-company-com
  secretName: cert-s3proxy-tls
  usages:
  - digital signature
  - key encipherment
{{- end }}