{{- if and (.Values.cert.commonName | not | empty) (.Values.cert.issuerRefName | not | empty) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-s3proxy-tls
spec:
  commonName: {{ .Values.cert.commonName | quote }}
  dnsNames:
  - {{ include "s3proxy.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ .Values.cert.issuerRefName | quote }}
  secretName: cert-s3proxy-tls
  usages:
  - digital signature
  - key encipherment
{{- end }}