{{- if and (.Values.config.accessKey | not | empty) (.Values.config.secretKey | not | empty) (.Values.config.encryptKey | not | empty) }}
apiVersion: v1
kind: Secret
metadata:
  name: s3proxy
data:
  accesskey: {{ .Values.config.accessKey | b64enc | quote }}
  secretkey: {{ .Values.config.secretKey | b64enc | quote }}
  encryptkey: {{ .Values.config.encryptKey | b64enc | quote }}
{{- end }}