{{- if and (.Values.valsSecret.accessKey | not | empty) (.Values.valsSecret.secretKey | not | empty) (.Values.valsSecret.encryptKey | not | empty) }}
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: s3proxy
spec:
  name: s3proxy
  ttl: 3600
  type: Opaque
  data:
    accesskey:
      ref: {{ .Values.valsSecret.accessKey }}
      encoding: text
    secretkey:
      ref: {{ .Values.valsSecret.secretKey }}
      encoding: text
    encryptkey:
      ref: {{ .Values.valsSecret.encryptKey }}
      encoding: text
{{- end }}